Test11 (#40)
* feat: debug

* feat: skip gh if ACT

* fix: if

* debug

* feat: ACT

* feat: ACT

* feat: ACT

* test

* feat: cleanup

* feat: act

* test

* feat: ACT

* test7

* test8

* test9

* test10

* test11

* feat: cleanup

diff --git a/.github/workflows/helm-charts.yaml b/.github/workflows/helm-charts.yaml
--- a/.github/workflows/helm-charts.yaml
+++ b/.github/workflows/helm-charts.yaml
@@ -147,7 +147,11 @@ jobs:
           INPUT_DO_RELEASE_BUILD: ${{ inputs.DO_RELEASE_BUILD }}
           INPUT_DO_PREVIEW_ENVIRONMENT: ${{ inputs.DO_PREVIEW_ENVIRONMENT }}
         run: |
-          if [ "${GH_REF}" = "refs/heads/master" ] || [ "${INPUT_DO_RELEASE_BUILD}" = "true" ]; then
+          if [ "${ACT}" ]; then
+            DO_RELEASE_BUILD="false"
+            DO_PREVIEW_ENVIRONMENT="false"
+            echo "If ${ACT}..."
+          elif [ "${GH_REF}" = "refs/heads/master" ] || [ "${INPUT_DO_RELEASE_BUILD}" = "true" ]; then
             DO_RELEASE_BUILD="true"
             DO_PREVIEW_ENVIRONMENT="false"
             echo "DEBUG: IF - INPUT_DO_RELEASE_BUILD : ${INPUT_DO_RELEASE_BUILD}"
@@ -165,6 +169,7 @@ jobs:
           HELM_REGISTRY_LOCATION=${{ inputs.HELM_DOCKER_REGISTRY }}/${{ inputs.GAR_PROJECT_ID }}/${{ inputs.HELM_REGISTRY_NAME }}/${{ inputs.NAME }}
           HELM_REGISTRY_URL="https://console.cloud.google.com/artifacts/docker/${{ inputs.GAR_PROJECT_ID }}/${{ inputs.LOCATION }}/${{ inputs.HELM_REGISTRY_NAME }}/${{ inputs.NAME }}?project=${{ inputs.GAR_PROJECT_ID }}/"
           # Display values
+          echo "ACT                    : ${ACT}"
           echo "DO_RELEASE_BUILD       : ${DO_RELEASE_BUILD}"
           echo "DO_PREVIEW_ENVIRONMENT : ${DO_PREVIEW_ENVIRONMENT}"
           echo "HELM_REGISTRY_LOCATION : ${HELM_REGISTRY_LOCATION}"
@@ -250,6 +255,7 @@ jobs:
           service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
 
       - name: "🔧 GKE credentials cluster: ${{ inputs.CLUSTER_NAME }}"
+        if: ${{ !env.ACT }}
         id: 'get-credentials'
         uses: 'google-github-actions/get-gke-credentials@v2'
         with:
@@ -309,6 +315,8 @@ jobs:
           cat Chart.yaml
           echo "DEBUG ==================== values.yaml"
           cat values.yaml
+          # echo "forcing failure"
+          # exit 9
 
 # yamllint enable rule:line-length
 
@@ -338,13 +346,15 @@ jobs:
         if: inputs.HELM_ADD_REPOS == true
         env:
           SCRIPT_NAME: ${{ inputs.HELM_ADD_REPOS_SCRIPT_NAME }}
+          BRANCH_NAME: master
         working-directory: ${{ inputs.SCRIPTS_DIR }}
         run: |
-          wget -O ./${SCRIPT_NAME} ${{ inputs.SCRIPTS_DOWNLOAD_BASE_URL }}/master/scripts/${SCRIPT_NAME}
+          wget -O ./${SCRIPT_NAME} ${{ inputs.SCRIPTS_DOWNLOAD_BASE_URL }}/${BRANCH_NAME}/scripts/${SCRIPT_NAME}
           chmod 777 ./${SCRIPT_NAME}
           ./${SCRIPT_NAME}
 
       - name: "🔧 [GAR] (oci://): Helm login"
+        if: ${{ !env.ACT }}
         working-directory: ${{ steps.set-charts-dir.outputs.CHARTS_DIR }}
         env:
           HELM_DOCKER_REGISTRY: ${{ inputs.HELM_DOCKER_REGISTRY }}
