fixt: FAN-6956 set-secrets

diff --git a/.github/workflows/setup-get-secrets.yaml b/.github/workflows/setup-get-secrets.yaml
--- a/.github/workflows/setup-get-secrets.yaml
+++ b/.github/workflows/setup-get-secrets.yaml
@@ -65,11 +65,20 @@ jobs:
             secret_key=$(echo "$secret" | cut -d'|' -f2)
             echo "secret_key  : ${secret_key}"
 
-            secret_value=${{ steps.get-secrets.outputs[$secret_key] }}
-            # echo "secret_value  : ${secret_value}"
+            # Access the secret value from step outputs using a temporary file
+            echo "${{ toJson(steps.get-secrets.outputs) }}" > outputs.json
+            secret_value=$(jq -r --arg key "$secret_key" '.[$key]' outputs.json)
+
+            # Validate secret value
+            if [ -z "$secret_value" ] || [ "$secret_value" = "null" ]; then
+              echo "Error: Failed to retrieve secret for key $secret_key" >&2
+              exit 1
+            fi
 
             echo "Mask secret_value..."
             echo "::add-mask::$secret_value"
+
+            # Add to JSON object
             secrets_json=$(echo "$secrets_json" | jq --arg key "$secret_key" --arg value "$secret_value" '. += {($key): $value}')
           done
           echo "secrets_json :"
