fixt: FAN-6956 set-secrets

diff --git a/.github/workflows/setup-get-secrets.yaml b/.github/workflows/setup-get-secrets.yaml
--- a/.github/workflows/setup-get-secrets.yaml
+++ b/.github/workflows/setup-get-secrets.yaml
@@ -51,6 +51,7 @@ jobs:
         uses: google-github-actions/get-secretmanager-secrets@v2
         with:
           secrets: ${{ inputs.secrets-to-fetch }}
+          export_to_environment: true
 
       - name: "🕵️‍♂️ Set Secrets as Outputs"
         id: set-secrets
@@ -62,20 +63,22 @@ jobs:
             secret_name=$(echo "$secret" | cut -d':' -f1)
             echo "secret_name : ${secret_name}"
 
-            secret_key=$(echo "$secret" | cut -d':' -f2)
-            echo "secret_key  : ${secret_key}"
-            echo "steps.get-secrets.outputs :"
-            echo "${{ toJson(steps.get-secrets.outputs) }}" | jq .
+            secret_value=${!secret_name}
+            # secret_key=$(echo "$secret" | cut -d':' -f2)
+            # echo "secret_key  : ${secret_key}"
+            # echo "steps.get-secrets.outputs :"
+            # echo "${{ toJson(steps.get-secrets.outputs) }}" | jq .
 
             # Access the secret value from step outputs using a temporary file
-            echo "${{ toJson(steps.get-secrets.outputs) }}" > outputs.json
-            echo "outputs.json..."
-            secret_value=$(jq -r --arg key "$secret_key" '.[$key]' outputs.json)
-            echo "secret_value : ${secret_value}"
+            # echo "${{ toJson(steps.get-secrets.outputs) }}" > outputs.json
+            # echo "outputs.json..."
+            # secret_value=$(jq -r --arg key "$secret_key" '.[$key]' outputs.json)
+            # echo "secret_value : ${secret_value}"
 
             # Validate secret value
             if [ -z "$secret_value" ] || [ "$secret_value" = "null" ]; then
-              echo "Error: Failed to retrieve secret for key $secret_key" >&2
+              # echo "Error: Failed to retrieve secret for key $secret_key" >&2
+              echo "Error: Failed to retrieve secret for key $secret_name" >&2
               exit 1
             fi
 
@@ -83,8 +86,10 @@ jobs:
             echo "::add-mask::$secret_value"
 
             # Add to JSON object
-            secrets_json=$(echo "$secrets_json" | jq --arg key "$secret_key" --arg value "$secret_value" '. += {($key): $value}')
+            # secrets_json=$(echo "$secrets_json" | jq --arg key "$secret_key" --arg value "$secret_value" '. += {($key): $value}')
+            secrets_json=$(echo "$secrets_json" | jq --arg key "$secret_name" --arg value "$secret_value" '. += {($key): $value}')
           done
+
           echo "secrets_json :"
           echo "${secrets_json}" | jq .
           echo "secrets=$secrets_json" >> $GITHUB_OUTPUT
